/**
 * 자동 생성물 — 직접 수정 금지. `pnpm codegen`으로 재생성한다.
 * 원본(Source of Truth): docs/specs/openapi.yaml
 */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/auth/social/{provider}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 소셜 로그인(웹 OAuth) → 세션 쿠키 발급 */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          provider: "kakao" | "naver" | "apple" | "google";
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["SocialLoginRequest"];
        };
      };
      responses: {
        /** @description 로그인 성공. Set-Cookie sid=...; HttpOnly; Secure; SameSite=Lax */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["AuthResult"];
          };
        };
        400: components["responses"]["BadRequest"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 세션 갱신(refresh 회전) */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description CSRF 방어 토큰(쿠키 세션 기반 변경 요청 필수). */
          "X-CSRF-Token": components["parameters"]["CsrfHeader"];
        };
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 갱신됨(Set-Cookie 재발급) */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        401: components["responses"]["Unauthorized"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 로그아웃(세션 무효화) */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description CSRF 방어 토큰(쿠키 세션 기반 변경 요청 필수). */
          "X-CSRF-Token": components["parameters"]["CsrfHeader"];
        };
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 로그아웃됨 */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 내 프로필 조회 */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Profile"];
          };
        };
        401: components["responses"]["Unauthorized"];
      };
    };
    put?: never;
    post?: never;
    /** 계정/데이터 삭제 요청(소프트 삭제 후 퍼지) */
    delete: {
      parameters: {
        query?: never;
        header: {
          /** @description CSRF 방어 토큰(쿠키 세션 기반 변경 요청 필수). */
          "X-CSRF-Token": components["parameters"]["CsrfHeader"];
        };
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 삭제 요청 접수(비동기 퍼지) */
        202: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    /** 프로필 수정(목표 변경 시 프로그램 재구성 트리거) */
    patch: {
      parameters: {
        query?: never;
        header: {
          /** @description CSRF 방어 토큰(쿠키 세션 기반 변경 요청 필수). */
          "X-CSRF-Token": components["parameters"]["CsrfHeader"];
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["ProfileUpdate"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Profile"];
          };
        };
        400: components["responses"]["BadRequest"];
      };
    };
    trace?: never;
  };
  "/me/consents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 개인정보/약관 동의 기록(PIPA) */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description CSRF 방어 토큰(쿠키 세션 기반 변경 요청 필수). */
          "X-CSRF-Token": components["parameters"]["CsrfHeader"];
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Consent"][];
        };
      };
      responses: {
        /** @description 기록됨 */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/me/export": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 내 데이터 내보내기(비동기 생성) */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description CSRF 방어 토큰(쿠키 세션 기반 변경 요청 필수). */
          "X-CSRF-Token": components["parameters"]["CsrfHeader"];
        };
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 생성 요청 접수 */
        202: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              export_id: string;
              /** @example pending */
              status: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/me/calibration": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 간이 캘리브레이션(시작 무게 추정) */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description CSRF 방어 토큰(쿠키 세션 기반 변경 요청 필수). */
          "X-CSRF-Token": components["parameters"]["CsrfHeader"];
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** @enum {string} */
            method?: "survey" | "amrap";
            items?: {
              exercise_id?: string;
              /** @enum {string} */
              perceived_difficulty?: "easy" | "moderate" | "hard";
              amrap_weight?: number | null;
              amrap_reps?: number | null;
            }[];
          };
        };
      };
      responses: {
        /** @description 초기 e1RM 산출 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Estimated1RM"][];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/programs/generate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 룰 기반 프로그램 생성 */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description CSRF 방어 토큰(쿠키 세션 기반 변경 요청 필수). */
          "X-CSRF-Token": components["parameters"]["CsrfHeader"];
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          /**
           * @example {
           *       "goal": "hypertrophy",
           *       "days_per_week": 4,
           *       "minutes_per_day": 60,
           *       "experience_level": "intermediate",
           *       "equipment": [
           *         "barbell",
           *         "dumbbell",
           *         "machine"
           *       ],
           *       "avoid_exercises": [
           *         "e_back_squat"
           *       ],
           *       "pain_areas": [
           *         "knee"
           *       ]
           *     }
           */
          "application/json": components["schemas"]["GenerateProgramRequest"];
        };
      };
      responses: {
        /** @description 생성됨 */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Program"];
          };
        };
        400: components["responses"]["BadRequest"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/programs/current": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 현재 프로그램 조회 */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Program"];
          };
        };
        404: components["responses"]["NotFound"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/programs/{programId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** 프로그램 수정(세트수 등, 변경 사유 로깅) */
    patch: {
      parameters: {
        query?: never;
        header: {
          /** @description CSRF 방어 토큰(쿠키 세션 기반 변경 요청 필수). */
          "X-CSRF-Token": components["parameters"]["CsrfHeader"];
        };
        path: {
          programId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            edits?: {
              /** @enum {string} */
              op?: "set_count" | "swap_exercise" | "reorder";
              payload?: {
                [key: string]: unknown;
              };
            }[];
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Program"];
          };
        };
      };
    };
    trace?: never;
  };
  "/exercises": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 운동 카탈로그 조회(필터) */
    get: {
      parameters: {
        query?: {
          pattern?: string;
          equipment?: string;
          cursor?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              items: components["schemas"]["Exercise"][];
              next_cursor?: string | null;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/exercises/{exerciseId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 운동 상세 */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          exerciseId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Exercise"];
          };
        };
        404: components["responses"]["NotFound"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/exercises/{exerciseId}/recommendation": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 특정 운동의 다음 세션 추천(근거 포함) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          exerciseId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Recommendation"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sessions/{sessionId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 세션 + 계획세트(추천값 포함) 조회 */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          sessionId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Session"];
          };
        };
        404: components["responses"]["NotFound"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sessions/{sessionId}/complete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 세션 완료(피드백) → 추천 재계산 트리거 */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description CSRF 방어 토큰(쿠키 세션 기반 변경 요청 필수). */
          "X-CSRF-Token": components["parameters"]["CsrfHeader"];
        };
        path: {
          sessionId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            /** @enum {string} */
            difficulty?: "easy" | "moderate" | "hard";
            /** @enum {string} */
            pump?: "low" | "medium" | "high";
            pain?: number;
          };
        };
      };
      responses: {
        /** @description 완료 처리 및 다음 추천 반영 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              session: components["schemas"]["Session"];
              next_recommendations: components["schemas"]["Recommendation"][];
            };
          };
        };
        /** @description 잘못된 입력(difficulty/pump enum 밖, pain 이 0~10 범위 밖). */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description 세션이 없다(내 세션이 아닌 경우 포함). */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sync": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 오프라인 변경 배치 push + 변경 pull
     * @description client_id는 한 번의 로컬 변경을 식별하는 멱등 키이며 재시도에서만 재사용한다. 같은 entity_id의 변경은 (updated_at, client_id) 순서로 LWW를 판정한다. session_routine → performed_set → session 완료 순으로 적용하고, 완료 전에 같은 세션의 선행 mutation이 충돌하면 완료를 보류한다. pull은 서버 단조 증가 순서의 opaque cursor를 쓴다.
     */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description CSRF 방어 토큰(쿠키 세션 기반 변경 요청 필수). */
          "X-CSRF-Token": components["parameters"]["CsrfHeader"];
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          /**
           * @example {
           *       "since": "42",
           *       "mutations": [
           *         {
           *           "client_id": "3f1b7c92-6a1e-4d8f-9b2a-5c7e0a1d4e63",
           *           "entity": "performed_set",
           *           "entity_id": "8b0e6fcb-1645-4b59-8c4d-d1f3d4f4bb54",
           *           "op": "upsert",
           *           "updated_at": "2026-07-16T10:22:00Z",
           *           "payload": {
           *             "actual_weight": 62.5,
           *             "actual_reps": 9,
           *             "actual_rir": 2,
           *             "actual_time_sec": null,
           *             "pain_score": null,
           *             "completed": true
           *           }
           *         }
           *       ]
           *     }
           */
          "application/json": components["schemas"]["SyncRequest"];
        };
      };
      responses: {
        /** @description 적용 결과 + 변경 목록 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["SyncResponse"];
          };
        };
        400: components["responses"]["BadRequest"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/analytics/e1rm": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 운동별 e1RM 추세 */
    get: {
      parameters: {
        query: {
          exercise_id: string;
          from?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              exercise_id: string;
              points: {
                /** Format: date */
                date: string;
                e1rm: number;
              }[];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/analytics/volume": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 근육군별 주간 볼륨(hard sets) */
    get: {
      parameters: {
        query?: {
          week_start?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              muscle: string;
              hard_sets: number;
              avg_rir: number;
            }[];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/analytics/completion": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 주간 운동 완료율 */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** Format: date */
              week_start: string;
              completed: number;
              planned: number;
              rate: number;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/billing/checkout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 정기결제 시작(빌링키 발급 세션/파라미터 반환)
     * @description 국내 PG(PortOne/토스/카카오·네이버페이) 빌링키 등록을 위한 세션 생성.
     */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description CSRF 방어 토큰(쿠키 세션 기반 변경 요청 필수). */
          "X-CSRF-Token": components["parameters"]["CsrfHeader"];
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          /**
           * @example {
           *       "product_id": "pro_yearly",
           *       "success_url": "https://afc.example/billing/success",
           *       "fail_url": "https://afc.example/billing/fail"
           *     }
           */
          "application/json": components["schemas"]["CheckoutRequest"];
        };
      };
      responses: {
        /** @description PG 결제창/빌링 등록 파라미터 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["CheckoutResponse"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/billing/confirm": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 빌링키 확정 및 첫 결제 처리 → 엔타이틀먼트 부여 */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description CSRF 방어 토큰(쿠키 세션 기반 변경 요청 필수). */
          "X-CSRF-Token": components["parameters"]["CsrfHeader"];
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            billing_key: string;
            product_id: string;
          };
        };
      };
      responses: {
        /** @description 구독 활성화 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["SubscriptionStatus"];
          };
        };
        /** @description 결제 실패 */
        402: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/subscriptions/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 구독/엔타이틀먼트 상태 조회 */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["SubscriptionStatus"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/webhooks/pg": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * PG 웹훅(결제/갱신/해지/환불 상태 동기화)
     * @description 서명 검증 필수. 정기결제 자동갱신·실패·환불 이벤트를 반영.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** @example subscription.renewed */
            event_type: string;
            billing_key?: string;
            signature: string;
            data: {
              [key: string]: unknown;
            };
          };
        };
      };
      responses: {
        /** @description 처리됨 */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sessions/{sessionId}/exercises": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 오늘 루틴에 운동 추가(부위별 선택) */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description CSRF 방어 토큰(쿠키 세션 기반 변경 요청 필수). */
          "X-CSRF-Token": components["parameters"]["CsrfHeader"];
        };
        path: {
          sessionId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["AddExerciseRequest"];
        };
      };
      responses: {
        /** @description 갱신된 세션 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Session"];
          };
        };
        /** @description 잘못된 입력(exercise_id 누락, 존재하지 않는 exercise_id, sets 가 1~10 밖 등). */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description 세션이 없다(내 세션이 아닌 경우 포함). */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description 상태 충돌. **다른 날짜의** 종료된 세션은 편집할 수 없고(당일 세션은 종료 후에도 편집 가능 — F6-1), 같은 exercise_id 는 한 세션에 한 번만 넣을 수 있다. */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sessions/{sessionId}/exercises/{plannedExerciseId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** 오늘 루틴에서 운동 삭제 */
    delete: {
      parameters: {
        query?: never;
        header: {
          /** @description CSRF 방어 토큰(쿠키 세션 기반 변경 요청 필수). */
          "X-CSRF-Token": components["parameters"]["CsrfHeader"];
        };
        path: {
          sessionId: string;
          plannedExerciseId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 갱신된 세션 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Session"];
          };
        };
        /** @description 세션이 없거나 그 운동이 세션에 없다. */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description 상태 충돌. **다른 날짜의** 종료된 세션은 편집할 수 없고(당일 세션은 종료 후에도 편집 가능 — F6-1), 이미 수행 기록이 있는 운동은 뺄 수 없다. */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sessions/{sessionId}/exercises/{plannedExerciseId}/swap": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 오늘 루틴의 운동 교체(같은 부위 대체 우선) */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description CSRF 방어 토큰(쿠키 세션 기반 변경 요청 필수). */
          "X-CSRF-Token": components["parameters"]["CsrfHeader"];
        };
        path: {
          sessionId: string;
          plannedExerciseId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            to_exercise_id: string;
          };
        };
      };
      responses: {
        /** @description 갱신된 세션 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Session"];
          };
        };
        /** @description 잘못된 입력(to_exercise_id 누락, 존재하지 않는 to_exercise_id 등). */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description 세션이 없거나, 교체 대상 운동이 세션에 없다. */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description 상태 충돌. **다른 날짜의** 종료된 세션은 편집할 수 없고(당일 세션은 종료 후에도 편집 가능 — F6-1), 이미 수행 기록이 있는 운동은 교체할 수 없으며, 이미 이 세션에 있는 종목으로는 교체할 수 없다(중복 금지). */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sessions/ad-hoc": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 즉석 세션 생성(휴식일에도 운동하기 — 부위 선택)
     * @description FEATURES_UX F8-1. 현재 프로그램에 **오늘 날짜(UTC)** 세션을 만들고 선택한 부위의 루틴을 배정한다. 운동 선택·목표 반복·세트 수는 프로그램 생성과 같은 규칙이고, 프로그램 생성 때 적용한 통증 부위 제외(SAFETY_PAIN_MAPPING.md)도 그대로 적용된다. 이미 오늘 세션이 있으면 만들지 않고 409 — 클라이언트는 GET /dashboard 의 `today.session_id` 로 그 세션에 들어간다.
     */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description CSRF 방어 토큰(쿠키 세션 기반 변경 요청 필수). */
          "X-CSRF-Token": components["parameters"]["CsrfHeader"];
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          /**
           * @example {
           *       "body_part": "chest"
           *     }
           */
          "application/json": components["schemas"]["CreateAdHocSessionRequest"];
        };
      };
      responses: {
        /** @description 생성된 즉석 세션(계획세트 포함) */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Session"];
          };
        };
        /** @description 잘못된 입력(body_part 누락 또는 enum 밖의 값). */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description 프로그램이 없다(먼저 POST /programs/generate). */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description 오늘 이미 세션이 있다. 즉석 생성 대신 그 세션으로 이동한다 (세션 id 는 GET /dashboard 의 today.session_id). */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/dashboard": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 대시보드 요약(오늘/내일 상태 + 지표) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["DashboardSummary"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Error: {
      error: {
        /** @example VALIDATION_ERROR */
        code: string;
        message: string;
        details?: {
          [key: string]: unknown;
        } | null;
      };
    };
    SocialLoginRequest: {
      /** @description 소셜 OIDC 토큰/인가코드 */
      id_token: string;
      device_id?: string | null;
    };
    AuthResult: {
      csrf_token: string;
      user: {
        /** @example u_123 */
        id: string;
        is_new: boolean;
      };
    };
    Profile: {
      id: string;
      /** @enum {string} */
      sex: "male" | "female" | "other";
      birth_year: number;
      height_cm: number;
      weight_kg: number;
      body_fat_pct: number | null;
      /** @enum {string} */
      goal: "diet" | "hypertrophy" | "strength";
      /** @enum {string} */
      experience_level: "beginner" | "intermediate" | "advanced";
      days_per_week?: number;
      minutes_per_day?: number;
      /** @enum {string} */
      plan_tier: "free" | "pro";
    };
    ProfileUpdate: {
      weight_kg?: number;
      body_fat_pct?: number;
      /** @enum {string} */
      goal?: "diet" | "hypertrophy" | "strength";
      days_per_week?: number;
      minutes_per_day?: number;
      /** @enum {string} */
      experience_level?: "beginner" | "intermediate" | "advanced";
    };
    Consent: {
      /** @example privacy_policy */
      type: string;
      /** @example 2026-07-16 */
      version: string;
      granted: boolean;
    };
    GenerateProgramRequest: {
      /** @enum {string} */
      goal: "diet" | "hypertrophy" | "strength";
      days_per_week: number;
      /** @enum {integer} */
      minutes_per_day: 30 | 45 | 60 | 75 | 90;
      /** @enum {string} */
      experience_level: "beginner" | "intermediate" | "advanced";
      equipment?: string[];
      avoid_exercises?: string[];
      pain_areas?: (
        "knee" | "lower_back" | "shoulder" | "elbow" | "wrist" | "hip" | "neck" | "ankle"
      )[];
    };
    Program: {
      program_id: string;
      goal: string;
      /** @example upper_lower */
      split_type: string;
      /** @example 2026.08.1 */
      rules_version: string;
      excluded_exercises: {
        /** @example e_back_squat */
        exercise_id: string;
        /** @example knee */
        pain_area: string;
        /** @example squat */
        movement_pattern: string;
        /** @example 무릎 통증으로 squat 패턴을 제외했다(일반적 회피 가이드이며 의료적 조언이 아니다). */
        reason: string;
      }[];
      sessions: {
        /** @example MON */
        day: string;
        /** @example upper */
        focus: string;
        exercises: {
          exercise_id: string;
          sets: number;
          reps_low: number | null;
          reps_high: number | null;
          target_rir: number | null;
          rest_sec: number;
          time_low_sec?: number | null;
          time_high_sec?: number | null;
        }[];
      }[];
    };
    Exercise: {
      id: string;
      name_ko: string;
      name_en: string;
      movement_pattern: string;
      primary_muscles: string[];
      equipment: string;
      difficulty: string;
      /** @enum {string} */
      mechanic: "compound" | "isolation";
      /** @enum {string} */
      region: "upper" | "lower" | "core";
      /** @enum {string} */
      metric: "reps" | "time";
      step_kg: number | null;
      rep_range_low?: number;
      rep_range_high?: number;
      default_time_low_sec: number | null;
      default_time_high_sec: number | null;
      substitutions: string[];
      media_url: string | null;
    };
    Session: {
      id: string;
      program_id: string;
      /** @enum {string} */
      goal: "diet" | "hypertrophy" | "strength";
      /** Format: date */
      scheduled_date: string;
      /** @enum {string} */
      status: "scheduled" | "in_progress" | "completed";
      planned_sets: components["schemas"]["PlannedSet"][];
    };
    PlannedSet: {
      id: string;
      exercise_id: string;
      set_no: number;
      target_reps_low: number | null;
      target_reps_high: number | null;
      target_rir: number | null;
      rest_sec: number;
      target_time_low_sec?: number | null;
      target_time_high_sec?: number | null;
      recommended_weight: number | null;
      recommended_reps: number | null;
      /** @example WEIGHT_UP_REP_TARGET_MET */
      reason_code: string;
      confidence: number;
      rules_version: string;
    };
    PerformedSet: {
      planned_set_id?: string;
      actual_weight?: number | null;
      actual_reps?: number | null;
      actual_rir?: number | null;
      actual_time_sec?: number | null;
      pain_score?: number | null;
      completed?: boolean;
      /** Format: uuid */
      client_id?: string;
      /** Format: date-time */
      updated_at?: string;
    };
    Recommendation: {
      exercise_id: string;
      weight: number | null;
      reps_low: number | null;
      reps_high: number | null;
      sets: number;
      time_low_sec?: number | null;
      time_high_sec?: number | null;
      reason_code: string;
      confidence: number;
      /** @example 최근 3세트 모두 상단·RIR 2 → +2.5kg */
      explanation: string;
      rules_version: string;
    };
    Estimated1RM: {
      exercise_id: string;
      e1rm: number;
      /** @example epley */
      method: string;
      /** Format: date-time */
      computed_at: string;
    };
    SyncRequest: {
      /** @description 직전 SyncResponse.next_cursor. 서버 순서를 감춘 opaque cursor이며 시각이 아니다. */
      since?: string | null;
      mutations: components["schemas"]["Mutation"][];
    };
    Mutation: {
      /**
       * Format: uuid
       * @description 한 번의 로컬 변경 ID. 같은 변경의 네트워크 재시도에서만 재사용한다.
       */
      client_id: string;
      /** @enum {string} */
      entity: "performed_set" | "session_routine" | "session";
      /**
       * Format: uuid
       * @description performed_set은 planned_set_id, 나머지는 workout_session.id.
       */
      entity_id: string;
      /** @enum {string} */
      op: "upsert" | "delete";
      /**
       * Format: date-time
       * @description 클라이언트 변경 시각. 같은 entity_id의 LWW 1차 비교값.
       */
      updated_at: string;
      /** @description entity에 대응하는 payload. delete는 빈 객체를 허용하며 서비스가 entity/op 조합을 검증한다. */
      payload:
        | components["schemas"]["PerformedSetMutationPayload"]
        | components["schemas"]["SessionRoutineMutationPayload"]
        | components["schemas"]["SessionMutationPayload"];
    };
    PerformedSetMutationPayload: {
      actual_weight?: number | null;
      actual_reps?: number | null;
      actual_rir?: number | null;
      actual_time_sec?: number | null;
      pain_score?: number | null;
      completed?: boolean;
    };
    SessionRoutineMutationPayload: {
      /** @description 현재 세션의 운동 순서를 나타내는 전체 snapshot. */
      exercise_ids: string[];
      /** @description 오프라인에서 새로 만든 planned set의 임시 상관키. 기존 서버 planned set에는 보내지 않는다. 같은 correlation_id 재전송은 반드시 같은 서버 planned_set_id로 해석한다. */
      correlations?: components["schemas"]["PlannedSetCorrelation"][];
    };
    PlannedSetCorrelation: {
      /** Format: uuid */
      correlation_id: string;
      exercise_id: string;
      set_no: number;
    };
    PlannedSetMapping: {
      /** Format: uuid */
      correlation_id: string;
      /** Format: uuid */
      planned_set_id: string;
      planned_set: components["schemas"]["PlannedSet"];
    };
    SessionMutationPayload: {
      /** @enum {string} */
      status?: "completed";
      /** @enum {string} */
      difficulty?: "easy" | "moderate" | "hard";
      /** @enum {string} */
      pump?: "low" | "medium" | "high";
      pain?: number;
    };
    SyncResponse: {
      applied: string[];
      conflicts: {
        /** Format: uuid */
        client_id: string;
        /** Format: uuid */
        entity_id: string;
        /** @example stale_update */
        reason: string;
      }[];
      changes: {
        /** @enum {string} */
        entity: "performed_set" | "session_routine" | "session";
        /** Format: uuid */
        entity_id: string;
        /** @enum {string} */
        op: "upsert" | "delete";
        data: {
          [key: string]: unknown;
        } | null;
        /** @description JSON 정밀도 손실을 피하기 위한 10진 문자열. */
        server_seq: string;
      }[];
      /** @description 이번 요청의 routine correlation에 대응하는 권위 planned set. 응답 유실 재시도에도 동일하다. */
      planned_set_mappings: components["schemas"]["PlannedSetMapping"][];
      /** @description 마지막으로 관찰한 server_seq를 감싼 opaque cursor. */
      next_cursor: string;
    };
    CheckoutRequest: {
      /** @enum {string} */
      product_id: "pro_monthly" | "pro_yearly";
      success_url?: string;
      fail_url?: string;
    };
    CheckoutResponse: {
      /** @example portone */
      pg: string;
      checkout_url?: string | null;
      /** @description PG SDK 초기화 파라미터 */
      params?: {
        [key: string]: unknown;
      };
    };
    SubscriptionStatus: {
      /** @enum {string} */
      tier: "free" | "pro";
      /** @enum {string} */
      status: "trial" | "active" | "grace" | "expired" | "cancelled";
      product_id?: string | null;
      /** Format: date-time */
      started_at?: string | null;
      /** Format: date-time */
      renews_at?: string | null;
      /** Format: date-time */
      trial_ends_at?: string | null;
    };
    AddExerciseRequest: {
      exercise_id: string;
      sets?: number | null;
      position?: number | null;
    };
    CreateAdHocSessionRequest: {
      /**
       * @example chest
       * @enum {string}
       */
      body_part: "chest" | "back" | "shoulders" | "arms" | "legs" | "core";
    };
    DashboardSummary: {
      /** Format: date */
      date: string;
      today: {
        /** @enum {string} */
        status: "workout" | "rest" | "done";
        session_id: string | null;
        routine_summary: {
          exercise_count: number;
          focus: string;
        } | null;
        done_summary: {
          total_volume: number;
          sets_completed: number;
          pr_count: number;
        } | null;
      };
      tomorrow: {
        /** @enum {string} */
        status: "workout" | "rest";
        routine_summary: {
          exercise_count: number;
          focus: string;
        } | null;
      };
      streak_days: number;
      weekly_completion_rate: number;
    };
  };
  responses: {
    /** @description 잘못된 요청 */
    BadRequest: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description 인증 필요/만료 */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description 없음 */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
  };
  parameters: {
    /** @description CSRF 방어 토큰(쿠키 세션 기반 변경 요청 필수). */
    CsrfHeader: string;
    Cursor: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
