/**
 * 자동 생성물 — 직접 수정 금지. `pnpm codegen`으로 재생성한다.
 * 원본(Source of Truth): docs/specs/openapi.yaml
 */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/auth/social/{provider}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 소셜 로그인(웹 OAuth) → 세션 쿠키 발급 */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          provider: "kakao" | "naver" | "apple" | "google";
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["SocialLoginRequest"];
        };
      };
      responses: {
        /** @description 로그인 성공. Set-Cookie sid=...; HttpOnly; Secure; SameSite=Lax */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["AuthResult"];
          };
        };
        400: components["responses"]["BadRequest"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 세션 갱신(refresh 회전) */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description CSRF 방어 토큰(쿠키 세션 기반 변경 요청 필수). */
          "X-CSRF-Token": components["parameters"]["CsrfHeader"];
        };
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 갱신됨(Set-Cookie 재발급) */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        401: components["responses"]["Unauthorized"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 로그아웃(세션 무효화) */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description CSRF 방어 토큰(쿠키 세션 기반 변경 요청 필수). */
          "X-CSRF-Token": components["parameters"]["CsrfHeader"];
        };
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 로그아웃됨 */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 내 프로필 조회 */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Profile"];
          };
        };
        401: components["responses"]["Unauthorized"];
      };
    };
    put?: never;
    post?: never;
    /** 계정/데이터 삭제 요청(소프트 삭제 후 퍼지) */
    delete: {
      parameters: {
        query?: never;
        header: {
          /** @description CSRF 방어 토큰(쿠키 세션 기반 변경 요청 필수). */
          "X-CSRF-Token": components["parameters"]["CsrfHeader"];
        };
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 삭제 요청 접수(비동기 퍼지) */
        202: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    /** 프로필 수정(목표 변경 시 프로그램 재구성 트리거) */
    patch: {
      parameters: {
        query?: never;
        header: {
          /** @description CSRF 방어 토큰(쿠키 세션 기반 변경 요청 필수). */
          "X-CSRF-Token": components["parameters"]["CsrfHeader"];
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["ProfileUpdate"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Profile"];
          };
        };
        400: components["responses"]["BadRequest"];
      };
    };
    trace?: never;
  };
  "/me/consents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 개인정보/약관 동의 기록(PIPA) */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description CSRF 방어 토큰(쿠키 세션 기반 변경 요청 필수). */
          "X-CSRF-Token": components["parameters"]["CsrfHeader"];
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Consent"][];
        };
      };
      responses: {
        /** @description 기록됨 */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/me/export": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 내 데이터 내보내기(비동기 생성) */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description CSRF 방어 토큰(쿠키 세션 기반 변경 요청 필수). */
          "X-CSRF-Token": components["parameters"]["CsrfHeader"];
        };
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 생성 요청 접수 */
        202: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              export_id: string;
              /** @example pending */
              status: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/me/calibration": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 간이 캘리브레이션(시작 무게 추정) */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description CSRF 방어 토큰(쿠키 세션 기반 변경 요청 필수). */
          "X-CSRF-Token": components["parameters"]["CsrfHeader"];
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** @enum {string} */
            method?: "survey" | "amrap";
            items?: {
              exercise_id?: string;
              /** @enum {string} */
              perceived_difficulty?: "easy" | "moderate" | "hard";
              amrap_weight?: number | null;
              amrap_reps?: number | null;
            }[];
          };
        };
      };
      responses: {
        /** @description 초기 e1RM 산출 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Estimated1RM"][];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/programs/generate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 룰 기반 프로그램 생성 */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description CSRF 방어 토큰(쿠키 세션 기반 변경 요청 필수). */
          "X-CSRF-Token": components["parameters"]["CsrfHeader"];
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          /**
           * @example {
           *       "goal": "hypertrophy",
           *       "days_per_week": 4,
           *       "minutes_per_day": 60,
           *       "experience_level": "intermediate",
           *       "equipment": [
           *         "barbell",
           *         "dumbbell",
           *         "machine"
           *       ],
           *       "avoid_exercises": [
           *         "e_back_squat"
           *       ],
           *       "pain_areas": [
           *         "knee"
           *       ]
           *     }
           */
          "application/json": components["schemas"]["GenerateProgramRequest"];
        };
      };
      responses: {
        /** @description 생성됨 */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Program"];
          };
        };
        400: components["responses"]["BadRequest"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/programs/current": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 현재 프로그램 조회 */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Program"];
          };
        };
        404: components["responses"]["NotFound"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/programs/{programId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** 프로그램 수정(세트수 등, 변경 사유 로깅) */
    patch: {
      parameters: {
        query?: never;
        header: {
          /** @description CSRF 방어 토큰(쿠키 세션 기반 변경 요청 필수). */
          "X-CSRF-Token": components["parameters"]["CsrfHeader"];
        };
        path: {
          programId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            edits?: {
              /** @enum {string} */
              op?: "set_count" | "swap_exercise" | "reorder";
              payload?: {
                [key: string]: unknown;
              };
            }[];
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Program"];
          };
        };
      };
    };
    trace?: never;
  };
  "/exercises": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 운동 카탈로그 조회(필터) */
    get: {
      parameters: {
        query?: {
          pattern?: string;
          equipment?: string;
          cursor?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              items: components["schemas"]["Exercise"][];
              next_cursor?: string | null;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/exercises/{exerciseId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 운동 상세 */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          exerciseId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Exercise"];
          };
        };
        404: components["responses"]["NotFound"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/exercises/{exerciseId}/recommendation": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 특정 운동의 다음 세션 추천(근거 포함) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          exerciseId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Recommendation"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sessions/{sessionId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 세션 + 계획세트(추천값 포함) 조회 */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          sessionId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Session"];
          };
        };
        404: components["responses"]["NotFound"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sessions/{sessionId}/complete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 세션 완료(피드백) → 추천 재계산 트리거 */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description CSRF 방어 토큰(쿠키 세션 기반 변경 요청 필수). */
          "X-CSRF-Token": components["parameters"]["CsrfHeader"];
        };
        path: {
          sessionId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            /** @enum {string} */
            difficulty?: "easy" | "moderate" | "hard";
            /** @enum {string} */
            pump?: "low" | "medium" | "high";
            pain?: number;
          };
        };
      };
      responses: {
        /** @description 완료 처리 및 다음 추천 반영 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              session: components["schemas"]["Session"];
              next_recommendations: components["schemas"]["Recommendation"][];
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sync": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 오프라인 변경 배치 push + 변경 pull
     * @description client_id 멱등, updated_at 기준 LWW. 세션 완료 mutation 시 추천 재계산.
     */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description CSRF 방어 토큰(쿠키 세션 기반 변경 요청 필수). */
          "X-CSRF-Token": components["parameters"]["CsrfHeader"];
          /** @description 재시도 안전을 위한 멱등 키. */
          "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          /**
           * @example {
           *       "since": "2026-07-16T00:00:00Z",
           *       "mutations": [
           *         {
           *           "client_id": "m_9f2",
           *           "entity": "performed_set",
           *           "op": "upsert",
           *           "payload": {
           *             "planned_set_id": "ps_5",
           *             "actual_weight": 62.5,
           *             "actual_reps": 9,
           *             "actual_rir": 2,
           *             "completed": true,
           *             "updated_at": "2026-07-16T10:22:00Z"
           *           }
           *         }
           *       ]
           *     }
           */
          "application/json": components["schemas"]["SyncRequest"];
        };
      };
      responses: {
        /** @description 적용 결과 + 변경 목록 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["SyncResponse"];
          };
        };
        400: components["responses"]["BadRequest"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/analytics/e1rm": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 운동별 e1RM 추세 */
    get: {
      parameters: {
        query: {
          exercise_id: string;
          from?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              exercise_id: string;
              points: {
                /** Format: date */
                date: string;
                e1rm: number;
              }[];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/analytics/volume": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 근육군별 주간 볼륨(hard sets) */
    get: {
      parameters: {
        query?: {
          week_start?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              muscle: string;
              hard_sets: number;
              avg_rir: number;
            }[];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/analytics/completion": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 주간 운동 완료율 */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** Format: date */
              week_start: string;
              completed: number;
              planned: number;
              rate: number;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/billing/checkout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 정기결제 시작(빌링키 발급 세션/파라미터 반환)
     * @description 국내 PG(PortOne/토스/카카오·네이버페이) 빌링키 등록을 위한 세션 생성.
     */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description CSRF 방어 토큰(쿠키 세션 기반 변경 요청 필수). */
          "X-CSRF-Token": components["parameters"]["CsrfHeader"];
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          /**
           * @example {
           *       "product_id": "pro_yearly",
           *       "success_url": "https://afc.example/billing/success",
           *       "fail_url": "https://afc.example/billing/fail"
           *     }
           */
          "application/json": components["schemas"]["CheckoutRequest"];
        };
      };
      responses: {
        /** @description PG 결제창/빌링 등록 파라미터 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["CheckoutResponse"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/billing/confirm": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 빌링키 확정 및 첫 결제 처리 → 엔타이틀먼트 부여 */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description CSRF 방어 토큰(쿠키 세션 기반 변경 요청 필수). */
          "X-CSRF-Token": components["parameters"]["CsrfHeader"];
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            billing_key: string;
            product_id: string;
          };
        };
      };
      responses: {
        /** @description 구독 활성화 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["SubscriptionStatus"];
          };
        };
        /** @description 결제 실패 */
        402: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/subscriptions/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 구독/엔타이틀먼트 상태 조회 */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["SubscriptionStatus"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/webhooks/pg": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * PG 웹훅(결제/갱신/해지/환불 상태 동기화)
     * @description 서명 검증 필수. 정기결제 자동갱신·실패·환불 이벤트를 반영.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** @example subscription.renewed */
            event_type?: string;
            billing_key?: string;
            signature?: string;
            data?: {
              [key: string]: unknown;
            };
          };
        };
      };
      responses: {
        /** @description 처리됨 */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sessions/{sessionId}/exercises": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 오늘 루틴에 운동 추가(부위별 선택) */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description CSRF 방어 토큰(쿠키 세션 기반 변경 요청 필수). */
          "X-CSRF-Token": components["parameters"]["CsrfHeader"];
        };
        path: {
          sessionId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["AddExerciseRequest"];
        };
      };
      responses: {
        /** @description 갱신된 세션 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Session"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sessions/{sessionId}/exercises/{plannedExerciseId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** 오늘 루틴에서 운동 삭제 */
    delete: {
      parameters: {
        query?: never;
        header: {
          /** @description CSRF 방어 토큰(쿠키 세션 기반 변경 요청 필수). */
          "X-CSRF-Token": components["parameters"]["CsrfHeader"];
        };
        path: {
          sessionId: string;
          plannedExerciseId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 갱신된 세션 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Session"];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sessions/{sessionId}/exercises/{plannedExerciseId}/swap": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 오늘 루틴의 운동 교체(같은 부위 대체 우선) */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description CSRF 방어 토큰(쿠키 세션 기반 변경 요청 필수). */
          "X-CSRF-Token": components["parameters"]["CsrfHeader"];
        };
        path: {
          sessionId: string;
          plannedExerciseId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            to_exercise_id: string;
          };
        };
      };
      responses: {
        /** @description 갱신된 세션 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Session"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/dashboard": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 대시보드 요약(오늘/내일 상태 + 지표) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["DashboardSummary"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Error: {
      error: {
        /** @example VALIDATION_ERROR */
        code: string;
        message: string;
        details?: {
          [key: string]: unknown;
        } | null;
      };
    };
    SocialLoginRequest: {
      /** @description 소셜 OIDC 토큰/인가코드 */
      id_token: string;
      device_id?: string | null;
    };
    AuthResult: {
      csrf_token: string;
      user: {
        /** @example u_123 */
        id: string;
        is_new: boolean;
      };
    };
    Profile: {
      id: string;
      /** @enum {string} */
      sex: "male" | "female" | "other";
      birth_year: number;
      height_cm: number;
      weight_kg: number;
      body_fat_pct: number | null;
      /** @enum {string} */
      goal: "diet" | "hypertrophy" | "strength";
      /** @enum {string} */
      experience_level: "beginner" | "intermediate" | "advanced";
      days_per_week?: number;
      minutes_per_day?: number;
      /** @enum {string} */
      plan_tier: "free" | "pro";
    };
    ProfileUpdate: {
      weight_kg?: number;
      body_fat_pct?: number;
      /** @enum {string} */
      goal?: "diet" | "hypertrophy" | "strength";
      days_per_week?: number;
      minutes_per_day?: number;
      /** @enum {string} */
      experience_level?: "beginner" | "intermediate" | "advanced";
    };
    Consent: {
      /** @example privacy_policy */
      type: string;
      /** @example 2026-07-16 */
      version: string;
      granted: boolean;
    };
    GenerateProgramRequest: {
      /** @enum {string} */
      goal: "diet" | "hypertrophy" | "strength";
      days_per_week: number;
      /** @enum {integer} */
      minutes_per_day: 30 | 45 | 60 | 75 | 90;
      /** @enum {string} */
      experience_level: "beginner" | "intermediate" | "advanced";
      equipment?: string[];
      avoid_exercises?: string[];
      pain_areas?: string[];
    };
    Program: {
      program_id: string;
      goal: string;
      /** @example upper_lower */
      split_type: string;
      /** @example 2026.07.1 */
      rules_version: string;
      sessions: {
        /** @example MON */
        day: string;
        /** @example upper */
        focus: string;
        exercises: {
          exercise_id: string;
          sets: number;
          reps_low: number;
          reps_high: number;
          target_rir: number;
          rest_sec: number;
        }[];
      }[];
    };
    Exercise: {
      id: string;
      name_ko: string;
      name_en: string;
      movement_pattern: string;
      primary_muscles: string[];
      equipment: string;
      difficulty: string;
      rep_range_low?: number;
      rep_range_high?: number;
      substitutions: string[];
      media_url: string | null;
    };
    Session: {
      id: string;
      program_id: string;
      /** Format: date */
      scheduled_date: string;
      /** @enum {string} */
      status: "scheduled" | "in_progress" | "completed";
      planned_sets: components["schemas"]["PlannedSet"][];
    };
    PlannedSet: {
      id: string;
      exercise_id: string;
      set_no: number;
      target_reps_low: number;
      target_reps_high: number;
      target_rir: number;
      rest_sec: number;
      recommended_weight: number;
      recommended_reps: number;
      /** @example WEIGHT_UP_REP_TARGET_MET */
      reason_code: string;
      confidence: number;
      rules_version: string;
    };
    PerformedSet: {
      planned_set_id?: string;
      actual_weight?: number;
      actual_reps?: number;
      actual_rir?: number | null;
      pain_score?: number | null;
      completed?: boolean;
      /** Format: uuid */
      client_id?: string;
      /** Format: date-time */
      updated_at?: string;
    };
    Recommendation: {
      exercise_id: string;
      weight: number;
      reps_low: number;
      reps_high: number;
      sets: number;
      reason_code: string;
      confidence: number;
      /** @example 최근 3세트 모두 상단·RIR 2 → +2.5kg */
      explanation: string;
      rules_version: string;
    };
    Estimated1RM: {
      exercise_id: string;
      e1rm: number;
      /** @example epley */
      method: string;
      /** Format: date-time */
      computed_at: string;
    };
    SyncRequest: {
      /** Format: date-time */
      since?: string | null;
      mutations: components["schemas"]["Mutation"][];
    };
    Mutation: {
      /** Format: uuid */
      client_id: string;
      /** @enum {string} */
      entity: "performed_set" | "session" | "profile";
      /** @enum {string} */
      op: "upsert" | "delete";
      payload: {
        [key: string]: unknown;
      };
    };
    SyncResponse: {
      applied: string[];
      conflicts: {
        client_id: string;
        /** @example stale_update */
        reason: string;
      }[];
      changes: {
        entity: string;
        id: string;
        data: {
          [key: string]: unknown;
        };
      }[];
      next_cursor?: string;
    };
    CheckoutRequest: {
      /** @enum {string} */
      product_id: "pro_monthly" | "pro_yearly";
      success_url?: string;
      fail_url?: string;
    };
    CheckoutResponse: {
      /** @example portone */
      pg: string;
      checkout_url?: string | null;
      /** @description PG SDK 초기화 파라미터 */
      params?: {
        [key: string]: unknown;
      };
    };
    SubscriptionStatus: {
      /** @enum {string} */
      tier: "free" | "pro";
      /** @enum {string} */
      status: "trial" | "active" | "grace" | "expired" | "cancelled";
      product_id?: string | null;
      /** Format: date-time */
      started_at?: string | null;
      /** Format: date-time */
      renews_at?: string | null;
      /** Format: date-time */
      trial_ends_at?: string | null;
    };
    AddExerciseRequest: {
      exercise_id: string;
      sets?: number | null;
      position?: number | null;
    };
    DashboardSummary: {
      /** Format: date */
      date: string;
      today: {
        /** @enum {string} */
        status: "workout" | "rest" | "done";
        routine_summary: {
          exercise_count: number;
          focus: string;
        } | null;
        done_summary: {
          total_volume: number;
          sets_completed: number;
          pr_count: number;
        } | null;
      };
      tomorrow: {
        /** @enum {string} */
        status: "workout" | "rest";
        routine_summary: {
          exercise_count: number;
          focus: string;
        } | null;
      };
      streak_days: number;
      weekly_completion_rate: number;
    };
  };
  responses: {
    /** @description 잘못된 요청 */
    BadRequest: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description 인증 필요/만료 */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description 없음 */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
  };
  parameters: {
    /** @description CSRF 방어 토큰(쿠키 세션 기반 변경 요청 필수). */
    CsrfHeader: string;
    /** @description 재시도 안전을 위한 멱등 키. */
    IdempotencyKey: string;
    Cursor: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
